[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_port = COM4
upload_port = COM4
upload_speed = 921600

build_flags =
  -D USER_SETUP_LOADED=1
  -D TFT_WIDTH=320
  -D TFT_HEIGHT=480
  -I fonts
  -include include/User_Setup.h

[env:esp32dev_ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = smart-display.local
extra_scripts = post:tools/use_fast_ota.py
